/**
 * exportIrreplaceable.ts — extract ONLY the data that cannot be re-fetched.
 *
 * WHY. market_cache.db is 2.84GB and gitignored, and the FMP premium tier expired
 * 2026-07-06. Re-running the fetchers on the free tier returns nulls, so a large part
 * of this database is genuinely unrecoverable if the disk dies. Supabase does NOT hold
 * it — the Supabase schema is only inference_results / symbol_snapshots / watchlist /
 * macro_snapshots, i.e. the outcome-tracking layer.
 *
 * The insight that makes this cheap: most of the 2.84GB is REPRODUCIBLE.
 *   daily_prices (8.26M)          -> re-fetchable from Yahoo (backfillDailyPrices.ts)
 *   benchmark_prices (267k)       -> re-fetchable from Yahoo/FRED
 *   event_features_daily (303k)   -> regenerated by reextractDailyEvents.ts
 *   training_events_v11 (338k)    -> regenerated by buildUnifiedTrainingSet.ts
 *   fred_data, edgar_filings      -> free public APIs
 * So a full-database backup mostly duplicates things we can rebuild on demand. Backing
 * up only the irreplaceable tables produces a far smaller artifact, which is what makes
 * it practical to keep copies in more than one place — and one copy on one machine is
 * not a backup.
 *
 * event_features is included deliberately: its features_json blobs embed the premium
 * values that were already extracted, so it carries premium data even though it is not
 * itself an fmp_* cache.
 *
 * Usage:
 *   npx tsx src/scripts/exportIrreplaceable.ts
 *   npx tsx src/scripts/exportIrreplaceable.ts --verify <file>   # integrity check
 */
import Database from 'better-sqlite3';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { existsSync, mkdirSync, statSync } from 'fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const SRC = join(ROOT, 'market_cache.db');

// Cannot be re-fetched: paid-tier FMP data, plus vendor caches whose historical
// point-in-time values are not served retroactively on free tiers.
const IRREPLACEABLE_PREFIXES = ['fmp_'];
const IRREPLACEABLE_EXACT = [
  'event_features',              // features_json embeds already-extracted premium values
  'congressional_trades_cache',
  'fda_cache',
  'finnhub_cache',
  'earnings_calendar',
  'historical_inference_results',
  'data_source_log',             // provenance for everything above
];
// Explicitly NOT copied — regenerable, and they are what makes the file huge.
const REPRODUCIBLE = [
  'daily_prices', 'benchmark_prices', 'event_features_daily',
  'training_events_v11', 'fred_data', 'edgar_filings',
];

function human(b: number): string {
  const u = ['B', 'KB', 'MB', 'GB'];
  let i = 0; let v = b;
  while (v >= 1024 && i < u.length - 1) { v /= 1024; i++; }
  return `${v.toFixed(1)} ${u[i]}`;
}

function main() {
  const argv = process.argv.slice(2);
  const verifyIdx = argv.indexOf('--verify');
  if (verifyIdx >= 0) {
    const f = argv[verifyIdx + 1];
    const db = new Database(f, { readonly: true });
    const integrity = db.pragma('integrity_check', { simple: true });
    const tables = db.prepare(
      "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all() as any[];
    let total = 0;
    console.log(`verifying ${f} (${human(statSync(f).size)})`);
    console.log(`integrity_check: ${integrity}`);
    for (const t of tables) {
      const n = (db.prepare(`SELECT COUNT(*) c FROM "${t.name}"`).get() as any).c;
      total += n;
      console.log(`   ${t.name.padEnd(38)} ${n.toLocaleString().padStart(12)}`);
    }
    console.log(`total rows: ${total.toLocaleString()}`);
    db.close();
    return;
  }

  if (!existsSync(SRC)) { console.error(`missing ${SRC}`); process.exit(1); }
  const outDir = join(ROOT, 'backups');
  mkdirSync(outDir, { recursive: true });
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const OUT = join(outDir, `irreplaceable_${stamp}.db`);
  if (existsSync(OUT)) { console.error(`${OUT} already exists — refusing to overwrite`); process.exit(1); }

  // The OUTPUT is the main connection: a read-only connection cannot ATTACH a new
  // writable file. The source is attached and only ever read from.
  const db = new Database(OUT);
  db.exec(`ATTACH DATABASE '${SRC.replace(/\\/g, '/')}' AS src`);

  const all = (db.prepare(
    "SELECT name, sql FROM src.sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
  ).all() as any[]);

  const chosen = all.filter(t =>
    IRREPLACEABLE_PREFIXES.some(p => t.name.startsWith(p)) || IRREPLACEABLE_EXACT.includes(t.name));

  console.log(`source: ${SRC} (${human(statSync(SRC).size)})`);
  console.log(`selecting ${chosen.length} irreplaceable tables; skipping ${REPRODUCIBLE.length} reproducible ones\n`);

  let totalRows = 0;
  for (const t of chosen) {
    const n = (db.prepare(`SELECT COUNT(*) c FROM src."${t.name}"`).get() as any).c;
    if (!n) { console.log(`   ${t.name.padEnd(38)} (empty, skipped)`); continue; }
    // recreate with the original schema so types/constraints survive, then copy
    try {
      db.exec(String(t.sql));
    } catch {
      db.exec(`CREATE TABLE "${t.name}" AS SELECT * FROM src."${t.name}" WHERE 0`);
    }
    db.exec(`INSERT INTO "${t.name}" SELECT * FROM src."${t.name}"`);
    totalRows += n;
    console.log(`   ${t.name.padEnd(38)} ${n.toLocaleString().padStart(12)}`);
  }
  db.exec('DETACH DATABASE src');
  db.close();

  const size = statSync(OUT).size;
  console.log(`\nwrote ${OUT}`);
  console.log(`   ${totalRows.toLocaleString()} rows, ${human(size)} ` +
              `(${(100 * size / statSync(SRC).size).toFixed(1)}% of the full database)`);
  console.log(`\nverify with:  npx tsx src/scripts/exportIrreplaceable.ts --verify "${OUT}"`);
}

main();
