#!/usr/bin/env npx tsx
/**
 * runSyntheticPotSweep.ts — Executes the 40,000-pot sweep.
 * File: src/scripts/runSyntheticPotSweep.ts
 *
 * Run with: npx tsx src/scripts/runSyntheticPotSweep.ts
 *
 * Loads synthetic_pots/pots_seed_20260709.json (generated by
 * generateSyntheticPots.ts) and walks each pot chronologically through the
 * 407-date historical_inference_results test fold via the real decidePot(),
 * exactly matching the chronological-loop design verified in recon. Processes
 * pots in chunks of 10,000 -- each pot's in-memory ledger is discarded right
 * after its final metrics + trade log are extracted, so at most one chunk's
 * worth of ledgers is ever held in memory at once, not all 40,000.
 *
 * Price resolution: exact daily_prices match -> nearest-prior-trading-day
 * fallback (<=10 calendar days) -> skip the event for that (symbol,date) if
 * neither resolves (matches the approved recon policy; the 306-row residual
 * gap from 28 symbols with zero daily_prices coverage is expected, not a bug).
 *
 * Writes to the two live tables: synthetic_pot_sweep_results (one row/pot)
 * and synthetic_pot_sweep_trades (one row per open/close action). Nothing in
 * PotService.ts is touched or imported for writing -- decidePot() is used
 * exactly as verified, its PotAction[] output is applied to an in-memory
 * ledger here, not to Supabase via applyPotActions (that's the live-pipeline
 * path; this is the backtest path decidePot's split was built to enable).
 */

import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { decidePot } from '../PotService';
import type { PotDecisionInput, PotAction } from '../PotService';
import { supabase } from '../db/supabaseClient';

const DATA_DIR = path.join(process.cwd(), 'synthetic_pots');
const CHUNK_SIZE = 10000;
const RESULTS_INSERT_BATCH = 2000;
const TRADES_INSERT_BATCH = 5000;

// ── Price resolution (exact -> fallback <=10d -> skip) ──────────────────────────

let priceIndex: Record<string, Array<[string, number]>>;

function resolvePrice(symbol: string, date: string): number | null {
  const series = priceIndex[symbol];
  if (!series || series.length === 0) return null;
  let lo = 0, hi = series.length - 1, exactIdx = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (series[mid][0] === date) { exactIdx = mid; break; }
    if (series[mid][0] < date) lo = mid + 1; else hi = mid - 1;
  }
  if (exactIdx !== -1) return series[exactIdx][1];
  const idx = lo - 1;
  if (idx < 0) return null;
  const targetMs = Date.parse(date + 'T00:00:00Z');
  const gapDays = (targetMs - Date.parse(series[idx][0] + 'T00:00:00Z')) / 86_400_000;
  if (gapDays > 10) return null;
  return series[idx][1];
}

function daysBetween(a: string, b: string): number {
  return Math.round((Date.parse(b + 'T00:00:00Z') - Date.parse(a + 'T00:00:00Z')) / 86_400_000);
}

// ── Types ────────────────────────────────────────────────────────────────────────

interface SyntheticPot {
  synthetic_pot_id: number; batch_id: string;
  boldness: number; ambition: number; patience: number;
  conviction: number; focus: number; reactivity: number;
  starting_balance: number;
}

interface TradeLogEntry {
  date: string; symbol: string; kind: 'open' | 'close';
  direction: string; reason: string; price: number;
  realisedPnl?: number; holdingDays?: number;
}

interface Ledger {
  openPositions: any[];
  nextPositionId: number;
  realisedPnlCumulative: number;
  portfolioValueSeries: number[];
  tradeLog: TradeLogEntry[];
  skippedForNoPrice: number;
}

function toResult(row: any) {
  return {
    symbol: row.symbol, companyName: row.symbol, recommendation: row.recommendation,
    model_a_confidence: row.model_a_confidence, model_b_return_1m: row.model_b_return_1m,
    model_c_max_drawdown: row.model_c_max_drawdown, model_d1_return_3m: row.model_d1_return_3m,
    model_d2_return_6m: row.model_d2_return_6m, model_d3_return_2d: row.model_d3_return_2d,
    model_d5_return_2w: row.model_d5_return_2w, risk_score: 0, risk_reward_ratio: 0,
    current_price: 0,
  };
}

let byDate: Record<string, any[]>;
let dates: string[];

function runPotThroughFold(pot: SyntheticPot): Ledger {
  const ledger: Ledger = {
    openPositions: [], nextPositionId: 1, realisedPnlCumulative: 0,
    portfolioValueSeries: [], tradeLog: [], skippedForNoPrice: 0,
  };

  for (const date of dates) {
    const dayRows = byDate[date];
    const results: any[] = [];
    const priceMap: Record<string, number> = {};

    for (const row of dayRows) {
      const price = resolvePrice(row.symbol, date);
      if (price == null) { ledger.skippedForNoPrice++; continue; }
      const r = toResult(row);
      r.current_price = price;
      results.push(r);
      priceMap[row.symbol] = price;
    }
    for (const pos of ledger.openPositions) {
      if (!(pos.symbol in priceMap)) {
        const p = resolvePrice(pos.symbol, date);
        if (p != null) priceMap[pos.symbol] = p;
      }
    }

    const input: PotDecisionInput = {
      pot: pot as any, results, openPositions: ledger.openPositions, priceMap,
      prevRealisedPnl: ledger.realisedPnlCumulative,
      runDateStr: `${date}T00:00:00.000Z`, todayStr: date,
    };
    const actions: PotAction[] = decidePot(input);

    for (const action of actions) {
      if (action.kind === 'close') {
        const closedPos = ledger.openPositions.find(p => p.id === action.positionId);
        ledger.openPositions = ledger.openPositions.filter(p => p.id !== action.positionId);
        ledger.realisedPnlCumulative += action.realisedPnl;
        ledger.tradeLog.push({
          date, symbol: action.symbol, kind: 'close', direction: action.tradeAction,
          reason: action.reason, price: action.exitPrice, realisedPnl: action.realisedPnl,
          holdingDays: closedPos ? daysBetween(closedPos.entry_date, date) : undefined,
        });
      } else if (action.kind === 'open') {
        ledger.openPositions.push({
          id: ledger.nextPositionId++, pot_id: pot.synthetic_pot_id, symbol: action.symbol,
          direction: action.direction, entry_date: action.entryDate, entry_price: action.entryPrice,
          shares: action.shares, position_size_gbp: action.positionSizeGbp,
          expected_return_at_entry: action.expectedReturnAtEntry, patience_horizon: action.patienceHorizonLabel,
          exit_deadline: action.exitDeadline, status: 'open',
        });
        ledger.tradeLog.push({ date, symbol: action.symbol, kind: 'open', direction: action.direction, reason: action.tradeReason, price: action.entryPrice });
      } else if (action.kind === 'snapshot') {
        ledger.portfolioValueSeries.push(action.portfolioValue);
      } else if (action.kind === 'positionUpdate') {
        const pos = ledger.openPositions.find(p => p.id === action.positionId);
        if (pos) pos.current_price = action.currentPrice;
      }
    }
  }

  return ledger;
}

// ── Metrics extraction ───────────────────────────────────────────────────────────

function computeMetrics(pot: SyntheticPot, ledger: Ledger, seed: number) {
  const series = ledger.portfolioValueSeries;
  const endingValue = series.length > 0 ? series[series.length - 1] : pot.starting_balance;
  const totalReturnPct = ((endingValue - pot.starting_balance) / pot.starting_balance) * 100;

  const periodReturns: number[] = [];
  for (let i = 1; i < series.length; i++) {
    if (series[i - 1] > 0) periodReturns.push((series[i] - series[i - 1]) / series[i - 1]);
  }
  let sharpe = 0;
  if (periodReturns.length > 1) {
    const mean = periodReturns.reduce((a, b) => a + b, 0) / periodReturns.length;
    const variance = periodReturns.reduce((a, b) => a + (b - mean) ** 2, 0) / periodReturns.length;
    const std = Math.sqrt(variance);
    sharpe = std > 0 ? (mean / std) * Math.sqrt(252) : 0;
  }

  let peak = series.length > 0 ? series[0] : pot.starting_balance;
  let maxDrawdownPct = 0;
  for (const v of series) {
    if (v > peak) peak = v;
    const dd = peak > 0 ? ((peak - v) / peak) * 100 : 0;
    if (dd > maxDrawdownPct) maxDrawdownPct = dd;
  }

  const closes = ledger.tradeLog.filter(t => t.kind === 'close');
  const wins = closes.filter(t => (t.realisedPnl ?? 0) > 0).length;
  const winRatePct = closes.length > 0 ? (wins / closes.length) * 100 : null;
  const avgHoldingDays = closes.length > 0
    ? closes.reduce((a, t) => a + (t.holdingDays ?? 0), 0) / closes.length
    : null;

  return {
    batch_id: pot.batch_id,
    synthetic_pot_id: pot.synthetic_pot_id,
    boldness: pot.boldness, ambition: pot.ambition, patience: pot.patience,
    conviction: pot.conviction, focus: pot.focus, reactivity: pot.reactivity,
    starting_balance: pot.starting_balance,
    seed,
    ending_value: Math.round(endingValue * 100) / 100,
    total_return_pct: Math.round(totalReturnPct * 10000) / 10000,
    sharpe: Math.round(sharpe * 10000) / 10000,
    max_drawdown_pct: Math.round(maxDrawdownPct * 10000) / 10000,
    win_rate_pct: winRatePct != null ? Math.round(winRatePct * 100) / 100 : null,
    trade_count: closes.length,
    avg_holding_days: avgHoldingDays != null ? Math.round(avgHoldingDays * 100) / 100 : null,
    events_skipped_no_price: ledger.skippedForNoPrice,
  };
}

// ── Batched insert helper ────────────────────────────────────────────────────────

async function insertInChunks(table: string, rows: any[], chunkSize: number): Promise<{ inserted: number; errors: string[] }> {
  let inserted = 0;
  const errors: string[] = [];
  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize);
    const { error } = await supabase.from(table).insert(chunk);
    if (error) {
      errors.push(`rows ${i}-${i + chunk.length}: ${error.message}`);
    } else {
      inserted += chunk.length;
    }
  }
  return { inserted, errors };
}

// ── Main ─────────────────────────────────────────────────────────────────────────

async function main() {
  const t0 = performance.now();

  console.log('Loading inputs...');
  let pots: SyntheticPot[] = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'pots_seed_20260709.json'), 'utf8'));
  const limit = process.env.SWEEP_LIMIT ? parseInt(process.env.SWEEP_LIMIT, 10) : null;
  if (limit) { pots = pots.slice(0, limit); console.log(`SWEEP_LIMIT=${limit} -- dry-run mode, only processing first ${limit} pots.`); }
  const foldRows: any[] = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'fold_rows.json'), 'utf8'));
  priceIndex = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'price_index.json'), 'utf8'));
  const SEED = 20260709;

  byDate = {};
  for (const row of foldRows) (byDate[row.date] = byDate[row.date] || []).push(row);
  dates = Object.keys(byDate).sort();

  console.log(`Loaded ${pots.length} pots, ${foldRows.length} fold rows across ${dates.length} dates, ${Object.keys(priceIndex).length} priced symbols.`);

  let totalResultsInserted = 0, totalTradesInserted = 0;
  const chunkErrors: Array<{ chunk: number; errors: string[] }> = [];

  for (let chunkStart = 0; chunkStart < pots.length; chunkStart += CHUNK_SIZE) {
    const chunkIdx = chunkStart / CHUNK_SIZE;
    const chunkPots = pots.slice(chunkStart, chunkStart + CHUNK_SIZE);
    const tChunk0 = performance.now();

    const resultsBuffer: any[] = [];
    const tradesBuffer: any[] = [];

    for (const pot of chunkPots) {
      const ledger = runPotThroughFold(pot);
      resultsBuffer.push(computeMetrics(pot, ledger, SEED));
      for (const t of ledger.tradeLog) {
        tradesBuffer.push({
          batch_id: pot.batch_id, synthetic_pot_id: pot.synthetic_pot_id,
          trade_date: t.date, symbol: t.symbol, kind: t.kind,
          direction: t.direction, reason: t.reason, price: t.price,
        });
      }
      // ledger goes out of scope here -- not retained
    }

    const tCompute = performance.now();
    const { inserted: rInserted, errors: rErrors } = await insertInChunks('synthetic_pot_sweep_results', resultsBuffer, RESULTS_INSERT_BATCH);
    const { inserted: tInserted, errors: tErrors } = await insertInChunks('synthetic_pot_sweep_trades', tradesBuffer, TRADES_INSERT_BATCH);
    const tWrite = performance.now();

    totalResultsInserted += rInserted;
    totalTradesInserted += tInserted;
    const allErrors = [...rErrors, ...tErrors];
    if (allErrors.length > 0) chunkErrors.push({ chunk: chunkIdx, errors: allErrors });

    console.log(`Chunk ${chunkIdx} (${chunkPots.length} pots): compute=${((tCompute - tChunk0) / 1000).toFixed(1)}s write=${((tWrite - tCompute) / 1000).toFixed(1)}s results=${rInserted}/${resultsBuffer.length} trades=${tInserted}/${tradesBuffer.length}${allErrors.length ? ` ERRORS=${allErrors.length}` : ''}`);
  }

  const t1 = performance.now();
  console.log(`\n=== SWEEP COMPLETE ===`);
  console.log(`Total wall-clock: ${((t1 - t0) / 1000 / 60).toFixed(2)} minutes`);
  console.log(`Total results rows inserted: ${totalResultsInserted} / ${pots.length}`);
  console.log(`Total trade rows inserted: ${totalTradesInserted}`);
  if (chunkErrors.length > 0) {
    console.log(`Chunks with errors: ${chunkErrors.length}`);
    console.log(JSON.stringify(chunkErrors, null, 2));
  } else {
    console.log('No errors encountered.');
  }
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
