import type { GatingVerdict } from "../QuantamentalGatingEngine";

/** Represents a basic stock asset. */
export interface StockAsset {
  /** The ticker symbol */
  symbol: string;
  /** The company name */
  companyName: string;
}

/** Represents a market consisting of multiple stocks. */
export interface Market {
  /** The name of the market */
  name: string;
  /** The list of stocks in this market */
  stocks: StockAsset[];
}

/** Represents the classified market regime state. */
export interface MarketRegime {
  /** The broad market trend direction */
  trendRegime: "bull" | "bear" | "sideways";
  /** The ambient volatility level of the market */
  volatilityRegime: "low_volatility" | "normal" | "high_volatility" | "panic";
  /** The macroeconomic sentiment state */
  macroRegime: "risk_on" | "risk_off" | "transitioning";
}

/**
 * Detailed qualitative and quantitative analysis of a historical anomaly event.
 */
export interface StockAnalysis {
  /** Deprecated tag summarizing the catalyst */
  primary_catalyst_tag?: string;
  /** Top-level taxonomy category from EVENT_TAXONOMY (e.g. corporate, macro) */
  primaryCategory?: string;
  /** Sub-type within the primaryCategory (e.g. earnings_miss, fed_rate_decision) */
  primarySubType?: string;
  /** Up to two additional taxonomy categories if relevant */
  secondaryCategories?: string[];
  /** Freeform string tags describing the event */
  eventTags?: string[];
  /** Grounded Google search discoveries surrounding the event */
  suspected_catalyst: string;
  /** Key ongoing risk or implication going forward */
  key_risk: string;
  /** Deprecated overall confidence score (0-100) */
  confidence_score: number;
  /** Statistical confidence based on the magnitude (z-score) of the price and volume shock (0-100) */
  statisticalConfidence?: number;
  /** Causal confidence of the AI that the identified news genuinely drove the move (0-100) */
  causalConfidence?: number;
  catalyst_embedding?: string;
  risk_embedding?: string;
  causal_logic_score?: number;
  /** AI model's internal confidence in its own generation (0-100) */
  aiConfidence?: number;
  /** Confidence based on the size/quality of the historical dataset (0-100) */
  historicalConfidence?: number;
  /** Confidence based on the completeness of features available (0-100) */
  dataConfidence?: number;
  /** Numeric ranking from -100 (most negative) to +100 (most positive) impact */
  severity_score: number;
  /** True if the analysis was generated by the fallback rule-based system instead of Gemini */
  isFallback?: boolean;

  /** AI observations synthesizing alternative data (Trends, Wikipedia, YouTube, GDELT) */
  alternative_data_observations?: string;
  /** AI score (0-100) quantifying the overall abnormality and intensity of the combined alternative data signals */
  alternative_data_score?: number;

  /** AI observations synthesizing corporate governance data (EDGAR filings, Insider Trading, Friction Score) */
  corporate_governance_observations?: string;
  /** AI score (0-100) quantifying the severity and volume of governance events/friction/insider anomalies */
  corporate_governance_score?: number;

  /** AI observations synthesizing macroeconomic data */
  macroeconomic_observations?: string;
  /** AI score (0-100) quantifying macroeconomic structural stress or abnormality */
  macroeconomic_score?: number;

  /** AI observations synthesizing market structure and regimes */
  market_structure_observations?: string;
  /** AI score (0-100) quantifying structural liquidity and volume profiles */
  market_structure_score?: number;

  /** AI observations synthesizing company fundamentals and earnings/press releases */
  fundamental_and_earnings_observations?: string;
  /** AI score (0-100) quantifying the impact of fundamental or forward-guidance changes */
  fundamental_and_earnings_score?: number;

  max_favorable_excursion_1m?: number;
  max_adverse_excursion_1m?: number;
  market_cap_log10?: number;
  dollar_volume_30d?: number;
  sector_encoded?: number;
  event_type_encoded?: number;
  day_sin?: number;
  day_cos?: number;
  month_sin?: number;
  month_cos?: number;
  body_to_range_ratio?: number;
  volume_price_clustering?: number;
  overnight_gap_pct?: number;
  gap_fill_ratio?: number;
  relative_volume_30d?: number;
  dist_sma_50?: number;
  dist_sma_200?: number;
  rsi_14?: number;
  volatility_contraction_index?: number;
  days_since_macro_swing?: number;
  swing_type_encoded?: number;
  obv_delta_10d?: number;
  idiosyncratic_return?: number;
  peer_contagion_delta?: number;
  peer_average_return?: number;
  treasury_10y_yield?: number;
  congressional_net_flow_30d?: number;
  economic_policy_uncertainty?: number;
  management_confidence_score?: number;
  dark_pool_index?: number;
  ctb_velocity_7d?: number;
  short_interest_pct?: number;
  put_call_ratio_t_minus_1?: number;
  iv_crush_pct?: number;
  sector_excess_return?: number;
  short_interest_ratio?: number;
  options_put_call_ratio?: number;
  insider_cluster_density?: number;
  management_friction_score?: number;
  is_null_sample?: boolean | number;
  is_human_verified?: boolean;

  /** The value of the VIX ^VIX at the time of the event */
  vixAtEvent?: number;
  /** The categorized volatility regime at the time of the event */
  vixRegime?: string;
  /** The market regime state object mapping trend, volatility, and macro factors */
  marketRegime?: MarketRegime;
  /** Textual context about the broader macroeconomic state during the event */
  macroContext?: string;
  /** Flag indicating if this was classified primarily as a macro/sector systemic event */
  isSectorEvent?: boolean;

  /** FINRA short interest data point */
  shortInterest?: {
    shortInterestShares: number;
    shortInterestRatio: number; // days-to-cover
    pctOfFloat: number;
    settlementDate: string;
    source: "finra";
  };
  /** FINRA short interest velocity percent */
  shortInterestVelocity?: number | null;

  // Added dynamic features
  shannon_entropy_30d?: number;
  amihud_illiquidity_30d?: number;
  barycenter_stretch_20d?: number;
  kinetic_energy?: number;
  l1_lagrange_point?: number;
  orbital_escape_velocity?: number;
  escape_velocity_cleared?: number;
  market_reynolds_number?: number;
  fractal_efficiency_ratio_10d?: number;
  market_jerk?: number;
  seismic_magnitude_mw?: number;
  triggered_z_score_threshold?: number;
  sector_relative_z_score?: number;

  /** Short history of preceding anomaly events for the same stock */
  priorEvents?: Array<{
    date: string;
    primaryCategory: string;
    primarySubType: string;
    excessReturn: number;
    daysAgo: number;
  }>;
  /** Number of days since the most recent previous anomaly */
  daysSincePreviousEvent?: number;
  /** Total number of prior anomalies in the recent lookback window (e.g. 60 days) */
  eventDensity?: number;

  /** Real 1-day return historically realized from close to close */
  return_1d?: number;
  /** Real 1-week return historically realized */
  return_1w?: number;
  /** Real 1-month return historically realized */
  return_1m?: number;
  /** Real 6-month return historically realized */
  return_6m?: number;
  /** Real 1-year return historically realized */
  return_1y?: number;

  /** Anticipated 1-day effect score (-100 to 100) */
  effect_score_1d?: number;
  /** Anticipated 1-week effect score (-100 to 100) */
  effect_score_1w?: number;
  /** Anticipated 1-month effect score (-100 to 100) */
  effect_score_1m?: number;
  /** Anticipated 6-month effect score (-100 to 100) */
  effect_score_6m?: number;
  /** Anticipated 1-year effect score (-100 to 100) */
  effect_score_1y?: number;

  /** Direct snippet from search findings or reference texts */
  internet_findings?: string;
  /** Detailed explanation differentiating causal correlation vs mere coincidence */
  coincidence_vs_correlation?: string;
  /** Score from 0 to 100 of how closely correlated/causal this event was */
  correlation_confidence?: number;
  /** SEC EDGAR filings found near this date */
  edgarFilings?: EdgarFiling[];
  /** Days from near-by earnings report */
  daysFromEarnings?: number;
  /** Scheduled or actual earnings event near this anomaly */
  earningsContext?: EarningsEvent;
  /** Comprehensive macroeconomic snapshot on the event date */
  macroSnapshot?: MacroSnapshot;
  /** Scheduled economic calendar release for this date if outstanding */
  macroRelease?: MacroReleaseDetail;
  /** Social sentiment snapshot around the event date */
  socialSentiment?: SocialSentimentSummary;
  /** Wikipedia spikes detected for company or executives */
  wikipediaSpikes?: WikipediaTrafficSignal[];
  /** Google Trends summary centered on the anomaly date */
  trendsSummary?: TrendsSummary;
  /** Aggregated GDELT GKG tone summary for the anomaly date */
  gdeltTone?: GDELTToneSummary | null;
  /** Parsed YouTube transcripts (e.g. from earnings calls or CEO interviews) */
  youtubeVideos?: YouTubeVideo[];
  /** Processed news articles mapped to this anomaly */
  newsList?: NewsArticle[];

  fmp_social_sentiment_score?: number;
  fmp_social_post_volume?: number;
  fmp_news_sentiment_avg?: number;
  fmp_news_article_count_7d?: number;
  insider_net_shares_30d?: number | null;
  insider_buy_count_30d?: number | null;
  insider_sell_count_30d?: number | null;
  institutional_ownership_pct?: number | null;
  institutional_ownership_change_qoq?: number | null;
  eps_surprise_pct?: number | null;
  revenue_surprise_pct?: number | null;
  earnings_date_proximity_days?: number | null;
  analyst_upgrades_30d?: number | null;
  analyst_downgrades_30d?: number | null;
  price_target_consensus?: number | null;
  price_target_upside_pct?: number | null;
  google_trends_shock_ratio?: number;
}

export interface GDELTToneSummary {
  /** Average tone of GKG records whose Organizations field mentioned the company (null if no matches) */
  matchedToneAvg: number | null;
  /** Average tone across every GKG record that day, used as the z-score baseline */
  globalToneAvg: number | null;
  /** Standard deviation of tone across every GKG record that day */
  globalToneStdDev: number | null;
  /** Number of GKG records whose Organizations field mentioned the company */
  matchCount: number;
}

export interface YouTubeVideo {
  videoId: string;
  title: string;
  publishedAt: string;
  channelTitle: string;
  transcript?: string;
}

export interface EdgarFiling {
  accessionNumber: string; // (EDGAR's unique filing identifier)
  filedAt: string; // (ISO date of filing)
  form: string; // (form type: "8-K", "10-K", "10-Q", "4", "SC 13G", etc.)
  primaryDocument: string; // (filename of the main document)
  description: string; // (brief description of what was filed)
  filingUrl: string; // (direct URL to view the filing on EDGAR)
  issuingCik: string; // (company's Central Index Key)
  symbol: string;
}

export interface InsiderTransaction {
  filedAt: string;
  executiveName: string;
  executiveRole: string; // (officer title as reported in the filing)
  transactionDate: string;
  transactionType: string; // ("P" = purchase, "S" = sale, "A" = award/grant, "D" = disposition other than sale, "F" = tax withholding)
  shares: number;
  pricePerShare: number;
  totalValue: number;
  sharesOwnedAfter: number;
  isDirectOwnership: boolean; // (true = direct, false = indirect via trust/LLC etc)
  symbol: string;
  filingUrl: string;
  source: string; // (always "edgar")
}

export interface EdgarCompanyInfo {
  cik: string; // (Central Index Key — EDGAR's unique company identifier)
  symbol: string;
  name: string;
  sicCode: string;
  sicDescription: string;
  stateOfIncorporation: string;
  fiscalYearEnd: string;
  exchanges: string[];
}

/**
 * A uniform data point on a stock chart, containing standard price data, statistical features, and eventual anomaly analysis.
 */
export interface StockPoint {
  /** Standard YYYY-MM-DD date string */
  date: string;
  /** Unix timestamp in ms */
  timestamp: number;
  /** Open price */
  open: number;
  /** High price */
  high: number;
  /** Low price */
  low: number;
  /** Close price */
  close: number;
  /** Daily trading volume */
  volume: number;
  /** Simple 1-day percent return (close vs previous close) */
  dailyReturn: number;
  /** Return relative to the benchmark SP500, separating beta motion */
  excessReturn?: number;
  /** Absolute Average True Range (ATR) over 14 days */
  atr14?: number;
  /** The absolute daily move normalized against ambient ATR */
  atrNormalizedMove?: number;
  /** Severity proxy scaling the normalized ATR move */
  atrShockScore?: number;
  /** Ratio of today's volume to the rolling 30-day average volume */
  volumeRatio?: number;
  /** Synonym for volumeRatio, relative volume compared to average */
  relativeVolume?: number;
  /** Categorical tag of the volume ratio magnitude (e.g. "extreme", "elevated", "normal") */
  volumeShockType?: string | null;
  /** 30-day simple moving average of the daily returns (for anomaly detection) */
  rollingMean: number;
  /** 30-day standard deviation of the daily returns (for anomaly detection) */
  rollingStd: number;
  /** Calculates how many standard deviations the daily return lies from the mean */
  zScore: number;
  /** True if the magnitude of the z-score exceeds the threshold (e.g., 2.5) */
  isAnomaly: boolean;
  /** True if qualitative analysis has been attached to this point */
  hasAnalysis?: boolean;
  /** Detailed qualitative and quantitative analysis of this anomaly event */
  analysis?: StockAnalysis;

  body_to_range_ratio?: number;
  overnight_gap_pct?: number;
  volume_price_clustering?: number;
  volatility_contraction_index?: number;
  obv_delta_10d?: number;
  day_sin?: number;
  day_cos?: number;
  month_sin?: number;
  month_cos?: number;
  gap_fill_ratio?: number;
  congressional_net_flow_30d?: number;
  economic_policy_uncertainty?: number;
  management_confidence_score?: number;
  iv_crush_pct?: number;
  peer_contagion_delta?: number;
  peer_average_return?: number;

  [key: string]: any;
  gatingVerdict?: GatingVerdict;
  nonEventReason?: string;
}

/**
 * Lightweight structured point purely for charting display.
 */
export interface ChartPoint {
  /** Standard YYYY-MM-DD date string */
  date: string;
  /** Unix timestamp in ms */
  timestamp: number;
  /** Close price of the day */
  price: number;
  /** Trading volume */
  volume: number;
  /** Calculates how many standard deviations the daily return lies from the mean */
  zScore: number;
  /** 30-day simple moving average of daily returns */
  rollingMean: number;
  /** True if this is an anomaly event */
  isAnomaly: boolean;
  /** Simple 1-day percent return */
  dailyReturn: number;
}

/**
 * A feature vector representing the statistical input to similarity matching and analysis models.
 */
export interface EventFeatureVector {
  /** The ticker symbol */
  symbol: string;
  /** Date of the event */
  date: string;
  /** The daily return stripped of market beta (net of benchmark) */
  excessReturn: number;
  /** The standard deviation distance from the rolling mean */
  zScore: number;
  /** The absolute daily move normalized against ambient 14-day ATR */
  atrShockScore: number;
  /** The ratio of trading volume compared to rolling average */
  volumeRatio: number;
  /** Categorized severity of the volume ratio */
  volumeShockType: string | null;
  /** Value of the VIX ^VIX at event time */
  vixAtEvent: number | null;
  /** Categorized volatility regime at event time */
  vixRegime: string | null;
  /** Market trend regime at event time */
  trendRegime: string | null;
  /** Ambient market volatility regime at event time */
  volatilityRegime: string | null;
  /** Top-level taxonomy event category classification */
  primaryCategory: string | null;
  /** Sub-level taxonomy classification */
  primarySubType: string | null;
  /** Realized 1-day return (populated post-generation) */
  return_1d: number | null;
  /** Realized 1-week return */
  return_1w: number | null;
  /** Realized 1-month return */
  return_1m: number | null;
  /** Realized 6-month return */
  return_6m: number | null;
  /** Realized 1-year return */
  return_1y: number | null;
  
  forward_return_1d?: number;
  forward_return_1w?: number;
  forward_return_1m?: number;
  
  z_score?: number;
  vix_close?: number;
  /** Statistical confidence of the anomaly severity (0-100) */
  statisticalConfidence: number;
  /** Causal confidence in underlying catalyst identification (0-100) */
  causalConfidence: number | null;
  return_lag_vector: string;
  volume_lag_vector: string;

  triggered_z_score_threshold?: number;
  sector_relative_z_score?: number;

  max_favorable_excursion_1m?: number;
  max_adverse_excursion_1m?: number;
  market_cap_log10?: number;
  dollar_volume_30d?: number;
  gatingVerdict?: GatingVerdict;

  fmp_social_sentiment_score?: number;
  fmp_social_post_volume?: number;
  fmp_news_sentiment_avg?: number;
  fmp_news_article_count_7d?: number;
  insider_net_shares_30d?: number | null;
  insider_buy_count_30d?: number | null;
  insider_sell_count_30d?: number | null;
  institutional_ownership_pct?: number | null;
  institutional_ownership_change_qoq?: number | null;
  eps_surprise_pct?: number | null;
  revenue_surprise_pct?: number | null;
  earnings_date_proximity_days?: number | null;
  analyst_upgrades_30d?: number | null;
  analyst_downgrades_30d?: number | null;
  price_target_consensus?: number | null;
  price_target_upside_pct?: number | null;
  confidence_tier?: string | null;
  confidence_tier_high?: number | null;
  confidence_tier_medium?: number | null;
  confidence_tier_low?: number | null;
  google_trends_shock_ratio?: number;
  sector_encoded?: number;
  event_type_encoded?: number;
  day_sin?: number;
  day_cos?: number;
  month_sin?: number;
  month_cos?: number;
  body_to_range_ratio?: number;
  volume_price_clustering?: number;
  overnight_gap_pct?: number;
  gap_fill_ratio?: number;
  relative_volume_30d?: number;
  dist_sma_50?: number;
  dist_sma_200?: number;
  rsi_14?: number;
  volatility_contraction_index?: number;
  days_since_macro_swing?: number;
  swing_type_encoded?: number;
  obv_delta_10d?: number;
  idiosyncratic_return?: number;
  peer_contagion_delta?: number;
  peer_average_return?: number;
  treasury_10y_yield?: number;
  congressional_net_flow_30d?: number;
  economic_policy_uncertainty?: number;
  management_confidence_score?: number;
  dark_pool_index?: number;
  ctb_velocity_7d?: number;
  short_interest_pct?: number;
  put_call_ratio_t_minus_1?: number;
  iv_crush_pct?: number;
  sector_excess_return?: number;
  short_interest_ratio?: number;
  options_put_call_ratio?: number;
  insider_cluster_density?: number;
  management_friction_score?: number;
  is_null_sample?: boolean | number;
  is_human_verified?: boolean;

  shannon_entropy_30d?: number;
  amihud_illiquidity_30d?: number;
  barycenter_stretch_20d?: number;
  kinetic_energy?: number;
  l1_lagrange_point?: number;
  orbital_escape_velocity?: number;
  escape_velocity_cleared?: number;
  market_reynolds_number?: number;
  fractal_efficiency_ratio_10d?: number;
  market_jerk?: number;
  seismic_magnitude_mw?: number;

  signal_snapshot?: {
    // statistical
    excess_return: number | null;
    z_score: number | null;
    atr_shock_score: number | null;
    volume_ratio: number | null;
    shannon_entropy: number | null;
    amihud_illiquidity: number | null;
    fractal_efficiency: number | null;
    // market structure
    short_interest_pct_float: number | null;
    short_interest_velocity: number | null;
    put_call_ratio: number | null;
    iv_rank: number | null;
    dark_pool_index: number | null;
    // macro/regime
    vix: number | null;
    vix_regime: string | null;
    trend_regime: string | null;
    yield_curve_spread: number | null;
    credit_spread: number | null;
    macro_release_surprise: number | null;
    // alternative/social (normalised z-scores: gdelt/10, virality centred on 50, trends shock-1, etc.)
    gdelt_tone_z: number | null;
    stocktwits_virality_z: number | null;
    google_trends_z: number | null;
    wikipedia_spike_z: number | null;
    news_relevance_z: number | null;
    congressional_net_flow: number | null;
    // gating verdict summary
    event_classification: string | null;
    dominant_physics_regime: string | null;
    divergence_detected: boolean | null;
    // estimate revision momentum (period-over-period change in analyst EPS consensus)
    estimate_revision_direction: "up" | "down" | "flat" | null;
    estimate_revision_magnitude: number | null;
    // company-level credit proxy derived from D/E ratio (NOT a real spread; flagged as proxy)
    company_credit_proxy: number | null;
    // FMP news sentiment around the event window
    fmp_news_sentiment_avg: number | null;
    fmp_news_article_count_7d: number | null;
    // FMP insider trading in the 30 days before the event
    insider_net_shares_30d: number | null;
    // FMP institutional ownership at the closest quarter before the event
    institutional_ownership_pct: number | null;
  };
}

/**
 * Statistical summary of outcomes found via nearest-neighbor analogue analysis.
 */
export interface AnalogueOutcomeSummary {
  /** The number of valid analogues found */
  sampleSize: number;
  /** Mean 1-week return following analogues */
  averageReturn1w: number | null;
  /** Mean 1-month return following analogues */
  averageReturn1m: number | null;
  /** Mean 6-month return following analogues */
  averageReturn6m: number | null;
  /** Percentage of analogues with positive 1-month returns */
  winRate1m: number;
  /** Percentage of analogues with positive 6-month returns */
  winRate6m: number;
  /** Greatest minimum draw-down experienced within 1 month across analogues */
  maxDrawdown1m: number | null;
  /** Discrete distribution buckets of trajectory probabilities */
  probabilisticOutlook: {
    /** Probability bucket for strong rallies */
    strongRally: number;
    /** Probability bucket for mild rallies */
    mildRally: number;
    /** Probability bucket for sideways/range-bound */
    sideways: number;
    /** Probability bucket for mild declines */
    mildDecline: number;
    /** Probability bucket for strong declines/crashes */
    strongDecline: number;
  };
  /** Analyst note summarizing dataset significance */
  confidenceNote: string;
}

/**
 * A historical twin analogue that closely maps a recent anomaly.
 */
export interface SimilarEvent {
  /** The ticker symbol of the historic analogue */
  symbol: string;
  /** The date the analogue occurred */
  date: string;
  /** The cosine-similarity or euclidean distance metric match quality */
  similarityScore: number;
  /** The structural quantitative and context state at the time of analogue */
  features: EventFeatureVector;
  /** The actual trailing returns realized by the analogue */
  outcome: {
    /** Trailing 1-day return */
    return_1d: number | null;
    /** Trailing 1-week return */
    return_1w: number | null;
    /** Trailing 1-month return */
    return_1m: number | null;
    /** Trailing 6-month return */
    return_6m: number | null;
    /** Trailing 1-year return */
    return_1y: number | null;
  };
}

/**
 * Result object summarizing a full historical scan of a single stock ticker.
 */
export interface StockScanResult {
  rateLimitedSources?: string[];
  /** The stock ticker symbol */
  symbol: string;
  /** Company or entity name associated with the ticker */
  companyName: string;
  /** Currency code for the price data */
  currency: string;
  /** Standard Array of all daily historical points */
  points: StockPoint[];
  /** Subset of points that cross the anomaly threshold */
  anomalies: StockPoint[];
  /** High level metadata block about the underlying chart */
  meta: {
    /** The timescale range requested */
    range: string;
    /** Most recent closing price */
    regularMarketPrice: number | null;
    /** Previous close before the most recent bar */
    chartPreviousClose: number | null;
    /** The actual Z-score threshold applied, in case it was auto-adjusted */
    appliedZScoreThreshold?: number;
  };
  /** Notice regarding stale, incomplete, or otherwise questionable data feeds */
  dataQualityWarning?: string;
  /** Formatted, minified structural representation of the time series suitable for charting libraries */
  chartData?: ChartPoint[];
  /** Any top-level structural error related to this ticker */
  error?: string;
  /** FMP Company Context details */
  fmpCompanyContext?: {
    profile: any;
    ratios: any;
    recentEarnings: any[];
    upcomingEarnings: any[];
  };
  analyst_consensus_mean?: number;
  analyst_count?: number;
  visualization?: string;
}

/**
 * Represents a key executive's profile for background and network scanning.
 */
export interface ExecutiveProfile {
  /** Full name of the executive */
  name: string;
  /** Corporate title/role of the executive */
  role: string;
  /** Importance weight applied to events related to this role (0-100) */
  roleWeight: number;
  /** Found LinkedIn profile URL */
  linkedinUrl?: string;
  /** Found Twitter/X handle */
  twitterHandle?: string;
  /** Strings mapped to identified political networks or figures */
  knownPoliticalConnections?: string[];
  /** Strings mapped to other corporate boards or institutions */
  knownBusinessConnections?: string[];
}

/**
 * Event resulting from deep-web investigative reporting, social network crawling, or alternative data affecting an executive.
 */
export interface ExecutiveEvent {
  /** The name of the executive */
  executiveName: string;
  /** The role of the executive */
  executiveRole: string;
  /** The weight of their role in corporate impact */
  roleWeight: number;
  /** The date the alternative data signal occurred */
  eventDate: string;
  /** Categorization of the alternative intelligence signal */
  eventType:
    | "legal_issue"
    | "social_media_controversy"
    | "political_connection"
    | "personal_relationship"
    | "health_event"
    | "insider_transaction"
    | "public_statement"
    | "board_activity"
    | "competitor_meeting"
    | "regulatory_inquiry"
    | "lifestyle_event"
    | "departure_signal"
    | string;
  /** Initial inferred severity magnitude of the signal */
  eventSeverity: "low" | "moderate" | "high" | "critical";
  /** Short punchy headline */
  headline: string;
  /** Complete descriptive background text regarding the signal */
  detail: string;
  /** Original linking source URL if scraped */
  sourceUrl?: string;
  /** Whether confidence is bolstered by multiple confirming reports */
  isVerified: boolean;
  /** Derived structural materiality scale on price implications (0-100) */
  materialityScore: number;
  /** Argument for why this executive action affects equity value */
  stockRelevanceReason: string;
  /** Anticipated motion on price resulting from signal */
  potentialDirection: "bullish" | "bearish" | "neutral" | "uncertain";
  /** Anticipated scaling class of motion on price */
  potentialMagnitude: "negligible" | "minor" | "moderate" | "major" | "severe";
}

/**
 * Cumulative aggregate statistical profile outlining the unique characteristics of a specific stock.
 */
export interface StockProfile {
  /** The ticker symbol */
  symbol: string;
  /** Generation completion timestamp (ISO) */
  generatedAt: string;
  /** Count of historical anomalies included in building this profile */
  totalAnomaliesAnalysed: number;
  /** Mode class of primary categories seen across historical anomalies */
  mostCommonCatalystCategory: string;
  /** Mode class of primary sub-types seen across historical anomalies */
  mostCommonCatalystSubType: string;
  /** Mean average realized 1-month return post-anomalies */
  averageReturn1m: number;
  /** Mean average realized 6-month return post-anomalies */
  averageReturn6m: number;
  /** Percentage of historical anomalies where the 1-month trajectory inverted the initial shock magnitude */
  meanReversionRate: number;
  /** Percentage of events categorized structurally as non-idiosyncratic macro/sector beta plays */
  sectorEventRate: number;
  /** Arithmetic mean of statistical anomaly confidence */
  averageStatisticalConfidence: number;
  /** Arithmetic mean of causal catalyst attribution confidence */
  averageCausalConfidence: number;
  /** The highest absolute Z-score anomaly logged in the dataset, outlining the worst/best case severity */
  highestSeverityEvent: {
    /** The date of the highest severity anomaly */
    date: string;
    /** The inferred catalyst sub-type string */
    catalyst: string;
    /** The 1-year historic return post the worst severity event */
    return1y: number | null;
  } | null;
  /** 4-6 sentence AI-synthesized paragraph characterizing the personality of the stock's volume/price/causal behavior */
  profileSummary: string;
  /** Disclaimer clarifying the bounding sample size used to compute these statistics */
  dataNote: string;
}

/**
 * Tracked event for a competitor organization that exhibits potential spill-over effects.
 */
export interface CompetitorEvent {
  /** The ticker symbol of the competitor */
  competitorSymbol: string;
  /** The name of the competing corporation */
  competitorName: string;
  /** The date the competitive signal was discovered */
  eventDate: string;
  /** Internal classification of the competitor action */
  eventType:
    | "product_launch"
    | "executive_change"
    | "legal_issue"
    | "earnings_surprise"
    | "partnership"
    | "market_share_shift"
    | "regulatory_action"
    | "acquisition"
    | "bankruptcy"
    | "price_war"
    | string;
  /** Short punchy headline */
  headline: string;
  /** Detailed structural implication context */
  detail: string;
  /** Modeled directional impact applied to target cross-asset stock */
  impactOnTargetStock: "positive" | "negative" | "neutral" | "uncertain";
  /** Underlying structural mechanism driving the cross-asset spillover (e.g. Market share erosion) */
  impactReason: string;
  /** Anticipated severity on primary equity from competitor occurrence (0-100) */
  materialityScore: number;
}

/**
 * Top-level aggregation of alternative data and signals surrounding the management and competition footprint.
 */
export interface WikipediaTrafficSignal {
  articleTitle: string;
  queryTopic: string;
  baselineViewsAvg: number;
  spikeViewsAvg: number;
  anomalyDate: string;
  isSpike: boolean;
  spikeRatio: number;
}

export interface ExecutiveIntelligenceReport {
  /** The target stock ticker symbol */
  symbol: string;
  /** Compilation completion timestamp */
  reportDate: string;
  /** List of tracked management individuals */
  executivesScanned: string[];
  /** Wikipedia traffic spikes found 72h before event */
  wikipediaSpikes?: WikipediaTrafficSignal[];
  /** Array of signals associated with management */
  executiveEvents: ExecutiveEvent[];
  /** Array of verified management signals */
  verifiedEvents: ExecutiveEvent[];
  /** Array of management signals that lack multi-source corroboration */
  unverifiedEvents: ExecutiveEvent[];
  /** Signals discovered for known direct competitors */
  competitorEvents: CompetitorEvent[];
  /** The overarching directional indicator formulated across all alternative data components */
  overallSignal:
    | "bullish"
    | "bearish"
    | "neutral"
    | "mixed"
    | "insufficient_data";
  /** Cumulative risk/opportunity weighting scale derived from the dataset */
  overallMaterialityScore: number;
  /** Synthesized AI summary outlining the collective tail-risk or opportunity present in alternative signals */
  summary: string;
  /** Disclaimer clarifying the breadth of intelligence sources polled */
  searchCoverage: string;
}

export interface DataSourceRecord {
  sourceId: string; // (unique identifier e.g. "polygon", "yahoo", "edgar")
  sourceName: string; // (human-readable e.g. "Polygon.io", "Yahoo Finance")
  dataType: string; // (what kind of data: "price_ohlcv", "fundamentals", "news", "filings", "macro", "sentiment", "insider")
  symbol?: string; // (stock symbol this record relates to, if applicable)
  fetchedAt: string; // (ISO timestamp of when data was fetched)
  coverageStart?: string; // (earliest date covered by this fetch)
  coverageEnd?: string; // (latest date covered by this fetch)
  recordCount?: number; // (how many data points were returned)
  success: boolean; // (did the fetch succeed?)
  errorMessage?: string; // (if success is false, why did it fail?)
  latencyMs?: number; // (how long the fetch took in milliseconds)
  isFallback: boolean; // (true if this source is being used as a backup because the primary source failed)
  primarySourceId?: string; // (if isFallback is true, which source was supposed to provide this data?)
}

export interface PriceDataPoint {
  date: string; // (YYYY-MM-DD format)
  timestamp: number; // (Unix milliseconds)
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  vwap?: number; // (volume-weighted average price — only Polygon provides this)
  transactions?: number; // (number of trades — only Polygon provides this)
  source: string; // (always "polygon" for data from this service)
}

export interface PolygonNewsItem {
  id: string;
  publishedAt: string; // (ISO timestamp with minute precision)
  title: string;
  description?: string;
  articleUrl: string;
  tickers: string[]; // (all stock symbols mentioned in the article)
  source: string; // (publisher name e.g. "Reuters", "Bloomberg")
  sentiment?: {
    title: string; // (positive/negative/neutral)
    body?: string;
  };
}

export interface PolygonTickerDetails {
  symbol: string;
  name: string;
  market: string; // stocks, crypto, fx
  locale: string; // us, global
  primaryExchange: string;
  type: string; // CS=common stock, ETF, ADRC=ADR, etc.)
  active: boolean;
  currencyName: string;
  marketCap?: number;
  phoneNumber?: string;
  description?: string;
  sicCode?: string; // Standard Industry Classification code
  sicDescription?: string;
  totalEmployees?: number;
  listDate?: string;
  shareClassSharesOutstanding?: number;
  weightedSharesOutstanding?: number;
  source: string;
}

export interface CompanyProfile {
  symbol: string;
  name: string;
  price?: number;
  beta?: number;
  sector: string;
  industry: string;
  subIndustry?: string;
  exchange: string;
  marketCap: number;
  employees?: number;
  description: string;
  country: string;
  currency: string;
  ipoDate?: string;
  isActivelyTrading: boolean;
  source: string; // (always "fmp")
}

export interface CompanyFinancialRatios {
  symbol: string;
  date: string; // (most recent quarter end date)
  peRatio?: number;
  pegRatio?: number;
  priceToSalesRatio?: number;
  priceToBookRatio?: number;
  debtToEquityRatio?: number;
  currentRatio?: number;
  returnOnEquity?: number;
  returnOnAssets?: number;
  grossProfitMargin?: number;
  operatingProfitMargin?: number;
  netProfitMargin?: number;
  revenueGrowthYoY?: number;
  earningsGrowthYoY?: number;
  freeCashFlowPerShare?: number;
  source: string;
}

export interface EarningsEvent {
  symbol: string;
  reportDate: string; // (YYYY-MM-DD)
  fiscalQuarterEnd: string;
  estimatedEps?: number;
  actualEps?: number;
  epsSurprise?: number; // (actualEps - estimatedEps)
  epsSurprisePercent?: number;
  isUpcoming: boolean; // (true if reportDate is in the future)
  source: string;
}

export interface MacroDataPoint {
  seriesId: string; // (FRED series identifier e.g. "CPIAUCSL")
  seriesName: string; // (human-readable name)
  date: string;
  value: number;
  units: string; // (e.g. "Percent", "Index 1982-1984=100")
  source: string; // (always "fred")
}

export interface MacroSnapshot {
  date: string;
  vix?: number; // (from VIXCLS series)
  federalFundsRate?: number; // (from FEDFUNDS series)
  cpiYoY?: number; // (year-over-year CPI change, from CPIAUCSL)
  unemploymentRate?: number; // (from UNRATE)
  tenYearTreasury?: number; // (from DGS10 series)
  twoYearTreasury?: number; // (from DGS2 series)
  yieldCurvSpread?: number; // (10Y minus 2Y — negative = inverted = recession signal)
  creditSpread?: number; // (from BAMLH0A0HYM2 — high yield spread)
  dollarIndex?: number; // (from DTWEXBGS — broad dollar index)
  congressional_net_flow_30d?: number;
  economic_policy_uncertainty?: number;
  source: string;
}

export interface MacroReleaseDetail {
  releaseType: string; // ("cpi", "fomc", "nfp", "gdp")
  releaseDate: string;
  actualValue?: number;
  priorValue?: number;
  surprise?: number; // (actual minus prior, or actual minus consensus estimate)
  surpriseDirection: "beat" | "miss" | "in-line" | "unknown";
  isSignificant: boolean; // (true if surprise is more than 0.2 standard deviations from the distribution of historical surprises)
}

export interface NewsArticle {
  id: string; // (generated hash of url + publishedAt)
  publishedAt: string; // (ISO timestamp)
  title: string;
  description?: string;
  content?: string; // (first 200 chars — NewsAPI truncates free tier)
  url: string;
  sourceName: string; // (e.g. "Reuters", "Bloomberg", "CNBC")
  sourceId?: string; // NewsAPI's source identifier
  author?: string;
  relevanceScore?: number; // (computed by relevance ranking, 0-1)
  dataSource: string; // (always "newsapi")
  sentiment?: "positive" | "negative" | "neutral";
}

export interface SocialMention {
  postId: string;
  platform: string;
  title: string;
  selftext?: string;
  score: number;
  numComments: number;
  createdAt: string;
  url: string;
  flairText?: string;
  sentimentLabel: "bullish" | "bearish" | "neutral" | "ambiguous";
  sentimentScore: number;
  isHighEngagement: boolean;
  source: string;
}

export interface SocialSentimentSummary {
  symbol: string;
  fromDate: string;
  toDate: string;
  totalMentions: number;
  bullishCount: number;
  bearishCount: number;
  neutralCount: number;
  averageSentimentScore: number;
  highEngagementPosts: SocialMention[];
  sentimentTrend:
    | "accelerating_bullish"
    | "accelerating_bearish"
    | "stable"
    | "reversing"
    | "insufficient_data";
  viralityScore: number;
  source: string;
}

export interface TrendsDataPoint {
  date: string;
  value: number; // (0-100, where 100 = peak search volume in the period)
  keyword: string;
}

export interface TrendsSummary {
  symbol: string;
  companyName: string;
  fromDate: string;
  toDate: string;
  peakSearchDate: string;
  peakSearchValue: number;
  averageSearchValue: number;
  searchValueAtAnomaly: number; // (search volume on the anomaly date itself)
  searchValueDayBefore: number; // (leading indicator: was interest building?)
  isAboveBaseline: boolean; // (was search volume above its own 30-day average?)
  percentAboveBaseline: number;
  google_trends_shock_ratio?: number;
  source: string;
}

export interface SignalValidationEntry {
  name: string;
  sampleSize: number;
  /** Pearson linear correlation with forward return (null if insufficient data) */
  pearson: number | null;
  /** Spearman rank correlation = information coefficient (null if insufficient data) */
  spearman: number | null;
  /** Alias of spearman — the standard quant IC metric */
  informationCoefficient: number | null;
  /** Mean forward return when signal is in top quartile */
  meanReturnWhenHigh: number | null;
  /** Mean forward return when signal is in bottom quartile */
  meanReturnWhenLow: number | null;
  /** Plain-English summary of predictive strength */
  interpretation: string;
  /** Set when sampleSize < minEvents */
  insufficientData?: boolean;
  /** Per-category stats for categorical signals */
  categoryBreakdown?: {
    category: string;
    count: number;
    meanReturn: number;
    medianReturn: number;
  }[];
}

export interface SignalValidationReport {
  generatedAt: string;
  totalEventsAnalysed: number;
  horizon: "1d" | "1w" | "1m";
  signals: SignalValidationEntry[];
  /** Present when the dataset is too small for meaningful validation */
  datasetTooSmall?: {
    message: string;
    currentCount: number;
    suggestedTarget: number;
  };
}
